swagger: '2.0'
info:
  version: '0.1.0'
  title: User Api
  description: An API to manage users
host: localhost:8080
basePath: /api
schemes:
  - http
parameters:
  JWTToken:
    in: header
    name: jwttoken
    description: header containing a JWT Token
    type: string
    required: true
paths:
  /login:
    post:
      description: log with JWT token
      operationId: login
      consumes:
        - application/json
      parameters:
        - name: userCredentials
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserCredentials'
      responses:
        '201':
          description: logged in
          schema:
            $ref: '#/definitions/JWTToken'
        '401':
          description: Wrong user credentials
  /users:
    parameters:
      - $ref: '#/parameters/JWTToken'
    post:
      description: create a user
      operationId: register
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: user created
        '401':
          description: request not permitted
  /users/{email}:
    parameters:
      - in: path
        name: email
        required: true
        type: string
      - $ref: '#/parameters/JWTToken'
    get:
      description: get user informations
      operationId: getUserByEmail
      produces:
        - application/json
      responses:
        '201':
          description: user informations
          schema:
            $ref: '#/definitions/User'
        '401':
          description: unauthorized to check user
    patch:
      description: change user password
      operationId: patchPassword
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            properties:
              password:
                type: string
      responses:
        '201':
          description: updated password correctly
        '401':
          description: unauthorized to change password
definitions:
  User:
    type: object
    properties:
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      password:
        type: string
      admin:
        type: boolean
  UserCredentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  JWTToken:
    type: object
    properties:
      jwttoken:
        type: string